spring:
  application:
    name: "Lab02 Chat Ollama"
  main:
    web-application-type: none     # Do not start a web server.
  ai:
    retry:
      max-attempts: 1
      on-client-errors: false
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434

